### ISSUE TITLE
mysql specific functions

### ISSUE THREAD

**Issue by danmarsden** [learningworks/moodle-local_pages#1]
Hi there, 
I've just had an initial look at this to consider approval in the plugins db.

UNIX_TIMESTAMP is a mysql specific function - this will not work in other supported databases:
https://github.com/learningworks/moodle-local_pages/blob/master/lib.php#L74

**Comment by digitalskill** [comment]
Thanks for the feedback, I have updated the affected queries to use a timestamp passed in by PHP rather than the MYSQL function.
