### ISSUE TITLE
Checking for capability

### ISSUE THREAD

**Issue by mudrd8mz** [learningworks/moodle-local_pages#11]
There is no point of calling
```
if (!has_capability('local/pages:addpages', $context)) {
    require_capability('local/pages:addpages', $context);
}
```
All you need is just `require_capability()` call, right?

**Comment by mudrd8mz** [comment]
Same applies to other parts of the code like:
```
    require_sesskey();
    if (confirm_sesskey()) {
```
If the sesskey check is required, the if condition will always evaluate to to true - of the code flow reaches that if statement.

**Comment by digitalskill** [comment]
Agree - Updated code
