### ISSUE TITLE
PHP Notice when saving the form page

### ISSUE THREAD

**Issue by mudrd8mz** [learningworks/moodle-local_pages#13]
Attempting to save the form page, I got:
```
Notice: Undefined offset: 1 in /local/pages/renderer.php on line 442
```

**Comment by digitalskill** [comment]
form sending empty array element for the select box. (IT appears that if a select box has nothing selected - the element is not sent in some browsers)??.

Have updated script to ensure that new form rows have the default values selected preventing this.
