### ISSUE TITLE
Description could help more with the first steps

### ISSUE THREAD

**Issue by mudrd8mz** [learningworks/moodle-local_pages#17]
It might help for a new user if the plugin description had clear instructions for the first steps with the plugin - e.g. something like "go to Site administration > Plugins > Local plugins > Pages > Manage pages" and click "Add page" there.

These guidelines are important for all "local" plugins that have no unified place of appearance (such as activity modules or enrolments plugins).

**Comment by digitalskill** [comment]
Description updated
