### ISSUE TITLE
all pages are accessible anonymously.

### ISSUE THREAD

**Issue by danmarsden** [learningworks/moodle-local_pages#2]
this appears to be by design:
https://github.com/learningworks/moodle-local_pages/blob/master/index.php#L37

but there is no mention of this in the description/docs of the plugin.

If pages are really supposed to be accessbile anonymously - this should be made very clear in the readme and in the description of your plugin in the plugins db.

**Comment by digitalskill** [comment]
I have updated the readme in this Repo and will udpate the content areas so tha tusers area clear.

Page access is controlled when the page is created, capabilites can used to restrict/allow access.

**Comment by danmarsden** [comment]
Cool - It looked like you could just pass a different id to the index script and load every page you wanted to. Ideally it would be good if there was some form of check in the top of index.php to see if the page is public or not. If not public then use  require login and capability checks?

**Comment by huehu3hue** [comment]
`$pageid = required_param('id', PARAM_INT);

// Can do this.
if (!($page = $DB->get_record('local_pages_page', ['id' => $pageid])) {
    // Print some custom error message using a lang string.
    print_error('someidentifier', 'local_pages');
}

// Or this. Throws exception if record don't exist.
$page = $DB->get_record('local_pages_page', ['id' => $pageid], '*', MUST_EXIST);

if (!$page->ispublic) {
    require_login();
}`

**Comment by digitalskill** [comment]
Have updated the page index to passback if a cability is needed - require login is required if the page required a capability.

// Set the page layout.
$custompage     = custompage::load($pageid);

// Check if the page has an access level requirement.
$accesslevel    = $custompage->accesslevel;
if ($accesslevel != '') {
    require_login();
}

An id is not required to load a page, if the site supports htaccess files, the page can be loaded by a url as well - making for cleaner urls to load pages

**Comment by danmarsden** [comment]
cool - that should make it easier for others to review too..

I'd probably simplify it to a single line myself:
if (!empty($custompage->accesslevel)) {

but that's just me being picky... :-)
