### ISSUE TITLE
Travis CI Moodle 3.5+

### ISSUE THREAD

**Issue by Chocolate-lightning** [learningworks/moodle-local_pages#21]
Hey Kevin,

I see that your Travis runs are failing on tests running on PHP 5.6
I would suggest updating your .travis.yml to use the supported PHP versions in Moodle 3.5

You can find the dist file here: https://github.com/blackboard-open-source/moodle-plugin-ci/blob/master/.travis.dist.yml 

Kind regards,
Matt

**Comment by digitalskill** [comment]
Thanks Chocolate! Travis is now All updated
