### ISSUE TITLE
Orphaned Boost Navbar item

### ISSUE THREAD

**Issue by neilstapleton** [learningworks/moodle-local_pages#22]
It appears I've ended up with an orphaned item on the bottom of the [navbar](https://imgur.com/E8RHrfU) in Boost which I think was added by local_pages,  The item is simply called 'Pages plugin' and I suspect it's from where the local_pages plugin was previously installed a page created with 'Display on menu' ticked and then the page was deleted and/or the plugin was uninstalled. Can't seem to get rid of it.

If I uninstall the local_pages plugin it goes away, as soon as I re-install it comes back.

Best wishes
Neil

**Comment by digitalskill** [comment]
Hi Neil.

That is a new menu item. If a user has rights to the create pages - then this item will appear on the boost menu (We have had a lot of requests for this).

In this update - pages that are added to appear in the navigation block - will now appear in the boost menu.

**Comment by neilstapleton** [comment]
Hi Kevin.

Thanks for your work on the plugin and for the quick response. I hadn't realised it was a new feature. It makes sense now, are there some release notes or docs you can point me to so I can do a bit of RTFM?

Might be nice to provide a setting to enable or disable it for everyone including admins, I have a number of admins working on our site and pages is not something we need to change all that often, but that's a nice to have rather than a nessesity.

Thank again
Neil
