### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by dinism** [learningworks/moodle-local_pages#23]
I'm PT-PT translator.
Some sentences are hardcoded and it is not possible to translate them:
Examples:
In page "Manage Pages"
Add Page
PDF Manual
The button "Submit"
When adding/editing a page:
In Page Parent None is hardcoded.
In Display on menu Yes/No are hardcoded

Is it possible to tanslate 'page' and 'form' in the Type of page?
"Back to Page List" is hardcoded.
In Form Builder "Type" is hardcoded

It will be compatible to 3.6?
Thanks for the plugin

**Comment by digitalskill** [comment]
Updated Language strings for these areas.
This plugin is moodle 3.6 compatible.
