### ISSUE TITLE
Missing hideIf in construct

### ISSUE THREAD

**Issue by dustinbrisebois** [learningworks/moodle-local_pages#26]
Stack trace:
line 165 of /local/pages/forms/edit.php: Error thrown
line 194 of /lib/formslib.php: call to pages_edit_product_form->definition()
line 57 of /local/pages/forms/edit.php: call to moodleform->__construct()
line 410 of /local/pages/renderer.php: call to pages_edit_product_form->__construct()
line 56 of /local/pages/edit.php: call to local_pages_renderer->save_page()

**Comment by digitalskill** [comment]
Mform using Hideif is in use from Moodle 3.4 or higher. The latest version incorrectly stated that it suported version 3.0 to 3.3 - it does not.
However,
I have enabled an older version that supports these older versions of moodle that can be downloaded from: https://moodle.org/plugins/pluginversions.php?plugin=local_pages
