### ISSUE TITLE
Getting undefined method hideIf

### ISSUE THREAD

**Issue by dustinbrisebois** [learningworks/moodle-local_pages#27]
Exception - Call to undefined method MoodleQuickForm::hideIf()

Debug info: 
Error code: generalexceptionmessage

Stack trace:

line 165 of /local/pages/forms/edit.php: Error thrown
line 194 of /lib/formslib.php: call to pages_edit_product_form->definition()
line 57 of /local/pages/forms/edit.php: call to moodleform->__construct()
line 410 of /local/pages/renderer.php: call to pages_edit_product_form->__construct()
line 56 of /local/pages/edit.php: call to local_pages_renderer->save_page()

**Comment by digitalskill** [comment]
Hi, Older versions of Moodle (before 3.4) don't have hideif support. Have added a check in the code to ensure that this function is not called on older versions of Moodle.
Latest version has this support.
