### ISSUE TITLE
Invalid page layout specified

### ISSUE THREAD

**Issue by noisyjerm** [learningworks/moodle-local_pages#28]
The following error is displayed when viewing a page

Invalid page layout specified: map

    line 2463 of /lib/outputlib.php: call to debugging()
    line 2480 of /lib/outputlib.php: call to theme_config->layout_info_for_page()
    line 1298 of /lib/outputrenderers.php: call to theme_config->layout_file()
    line 74 of /local/pages/index.php: call to core_renderer->header()

To remedy change line 47 in index.php from $PAGE->set_pagelayout($templatename);
to
$PAGE->set_pagelayout('standard');
optionally create a special template for pages.

**Comment by digitalskill** [comment]
This can occur as the free text field has a change to support valid layouts only. Editing the page and saving again will resolve invalid theme templates references if they were entered.
