### ISSUE TITLE
direct access of $_POST not usually allowed

### ISSUE THREAD

**Issue by danmarsden** [learningworks/moodle-local_pages#3]
Typically direct access to $_POST/$_GET results in a failed review for inclusion in the plugins db and optional/required_param must be used - I haven't looked closely but you might possibly have some valid reasons for using $_POST - it's just really hard to read the code:
https://github.com/learningworks/moodle-local_pages/blob/00423b359c9c61a1269ca640b68ad6de0dc0679e/renderer.php#L193

If you really need to access $_POST directly I'd suggest you do it in a way that is much easier to review in your code, and see that you are sanitising the data correctly, possibly adding some code comments that justify why you can't use optional/required_param and we can review that a bit easier. This will also come up when other organisations perform a review on your code, so if you can rewrite it to use optional/required_param it will make it much easier for other organisations to use your plugin.

**Comment by digitalskill** [comment]
I'll update the pages plugin to use the Moodle Practise of Param items instead of depending on the global $_POST values.

**Comment by digitalskill** [comment]
Updated = Param values are dynamically created and passed in
