### ISSUE TITLE
Invalid get_string() identifier: 'cachedef_sent'

### ISSUE THREAD

**Issue by vavra5** [learningworks/moodle-local_pages#32]
Hello,

local_pages v1.7 (2019011107)

Doing some testing with Moodle v3.8.1 and I'm recieving this error when on the Cache administration page.  I'm not noticing any functional problems with the plugin.

I know your latest supported version for this plugin is v3.7, but I thought it would be good to report the issue to you.  Any thoughts or ideas for fixing this?

`Invalid get_string() identifier: 'cachedef_sent' or component 'local_pages'. Perhaps you are missing $string['cachedef_sent'] = ''; in /var/www/html/moodle/local/pages/lang/en/local_pages.php?
line 353 of /lib/classes/string_manager_standard.php: call to debugging()
line 10283 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 10317 of /lib/moodlelib.php: call to lang_string->get_string()
line ? of unknownfile: call to lang_string->__toString()
line 212 of /lib/classes/collator.php: call to Collator->asort()
line 322 of /lib/classes/collator.php: call to core_collator::asort()
line 246 of /cache/renderer.php: call to core_collator::asort_array_of_arrays_by_key()
line 316 of /cache/admin.php: call to core_cache_renderer->definition_summaries()`

**Comment by digitalskill** [comment]
Hi, 

Thanks for your feedback. So nice to have detailed informaiton. We have updated to resolve this error in the latest version (Moodle_39_stable) branch.
