### ISSUE TITLE
Form pages don't render for Moodle 3.9

### ISSUE THREAD

**Issue by dmitriim** [learningworks/moodle-local_pages#37]
In moodle 3.9 you still can create bunch of fields for your form page, but they don't get rendered on the page.

**Comment by Jay-Liya** [comment]
Can you please share a screenshot of the problem that you are having? It’s going to help us better understand your problem and we’ll be able to assist you better.

**Comment by dmitriim** [comment]
@Jay-Liya 

See I have created a bunch of fields for my contact form, however one the page itself the fields are not displayed.  I guess it's related to changed at some point a way to store the fields data in DB, but SQL is still trying to get them in an old way here https://github.com/learningworks/moodle-local_pages/blob/MOODLE_39_STABLE/renderer.php#L150

![image](https://user-images.githubusercontent.com/4626431/139957394-a0deba58-1940-46ee-ae15-efade3178a3b.png)
![image](https://user-images.githubusercontent.com/4626431/139957417-31c98631-62ee-4aba-9a26-a9e1d577bf54.png)

**Comment by Jay-Liya** [comment]
Hi, 
Thank you for your message.
the form itself not showing the added fields, 
create a page and a form
add fields in the form
in page content of the page add, {form}
in the form, select created page for "page parent"
when you "view" the page you can see the fields
when you go "edit" of the form you can see the all inserted data listed bottom of the form.
hope this will help you. :-)

**Comment by dmitriim** [comment]
Oh! Nice. That works this way now. Is there anywhere a documentation that describes it?

**Comment by dmitriim** [comment]
Looks like I'm blind and PDF link is located on the same page where the list of pages is.

**Comment by dmitriim** [comment]
I was able to send a message from my feedback form. However, after submitting I got following screen where {form} is displayed in the content. Am I missing something again? 

![image](https://user-images.githubusercontent.com/4626431/139968639-7311871e-321e-442b-9e4e-8473b3093c3d.png)

**Comment by Jay-Liya** [comment]
add {form} only in the "page content" of the page, not in the form

**Comment by dmitriim** [comment]
thanks a lot @Jay-Liya! Sorry for wasting your time...

**Comment by Jay-Liya** [comment]
No worries. :-)
