### ISSUE TITLE
missing sesskey checks on actions

### ISSUE THREAD

**Issue by danmarsden** [learningworks/moodle-local_pages#4]
https://github.com/learningworks/moodle-local_pages/blob/master/pages/pages.php#L45

this should really have a sesskey check as well - more info: 
https://docs.moodle.org/dev/Security:Cross-site_request_forgery

**Comment by digitalskill** [comment]
Have Updated to include require_sesskey and confirm_sesskey() for theis function.
Updated the delete button to inluce the sesskey parameter.
