### ISSUE TITLE
Tricky access to session superglobal

### ISSUE THREAD

**Issue by mudrd8mz** [learningworks/moodle-local_pages#9]
The code like this:
```
$_SESSION[$data->pagename] = "sent";
```
is not quite right:
* The user could mistakenly overwrite some existing session value if it collides with the page name.
* It uses the session superglobal directly.

if you need to access the session, you should use the `global $SESSION` wrapper or (maybe even better) have a dedicated session cache defined -
 https://docs.moodle.org/dev/The_Moodle_Universal_Cache_(MUC)#Session_cache

**Comment by digitalskill** [comment]
Used Cache working (Cheers @mudrd8mz for the link - very handy)
